### ISSUE TITLE
Title for section header

### ISSUE THREAD

**Issue by edpelesh** [GenericDataSource/GenericDataSource#1]
Is there any way to add or set title text for a section or datasource?

**Comment by mohamede1945** [comment]
Unfortunately not yet. It's planned to be added, though. For now, you can implement the table view header delegates in the outermost data source you have (the one assigned to be the delegate of the table view).

**Comment by edpelesh** [comment]
Ok, thanks a lot.

**Comment by ryanjm** [comment]
I've added the basics for table section header titles to my own [repo](https://github.com/ryanjm/GenericDataSource/tree/add-section-title), but I don't have any tests written for it yet (it does work in my own project though).

The part I'm not sure about is that collection views don't have a standard "header." Instead they have `viewForSupplementaryElementOfKind:`. I haven't used collection views very often so I'm not that comfortable with the various use cases, but it does seem like you'd want to supply your own `UIView` in the case of a `UICollectionView`.

@mohamede1945 What do you think the best way is to handle this?

Should GenericDataSource provide a basic `UIView` for a section header/footer for collection views? My guess is probably not.

Is it ok for `DataSource` to define some methods which would only apply to `UITableViewController`? This is what I'm doing right now, but this doesn't seem very clean to me.

The other ideas I have would be to:

1. Write another protocol / extension which you can add on to your datasource(s) to handle section titles.
2. Write fixed subclasses of `BasicDataSource` to use with `UICollectionView` vs `UITableView` (`BasicCollectionDataSource` vs `BasicTableDataSource`) where each can appropriately expand to handle unique aspects of the protocols. This removes some of the benefits of the generics (maybe?), but the generics would still work well for `DataSourcesCollection`.

Semi-related, and I haven't tested this out yet, but I wonder if having `heightForRowAtIndexPath` is going to backfire when it comes to dynamic cell heights and letting autolayout define the dimensions. I wonder if having an additional protocol that you could add to the class only if you need to customize the cell dimensions would work better. And I wonder if that would also clean up the need for `respondsToSelector` (which doesn't seem very swift-like). But honestly, I'm still getting my bearings straight when it comes to Swift so I'm not 100% sure using a protocol extension would even work for this or what is considered "swift-like" or not.

**Comment by mohamede1945** [comment]
Glad you have it work. I'll try to look at your implementation soon.

Regarding the section title. I was thinking about:
```Swift
func tableView(tableView: UITableView, viewForHeaderInSection section: Int) -> UIView?
func tableView(tableView: UITableView, viewForFooterInSection section: Int) -> UIView?
func collectionView(collectionView: UICollectionView, viewForSupplementaryElementOfKind kind: String, atIndexPath indexPath: NSIndexPath) -> UICollectionReusableView
```

So, I think the best way to support this is to support these methods. Also, I always think Apple should remove `UITableView` and instead have a layout called `UITableViewCollectionViewLayout` or something like that. Because the `UICollectionView` is a general way to handle stuff like that. So, I would say if you want to implement this one, then we can add to `DataSource` a method similar to 
```Swift
collectionView(collectionView: UICollectionView, viewForSupplementaryElementOfKind kind: String, atIndexPath indexPath: NSIndexPath) -> UICollectionReusableView
```

In general, I don't think the library should handle a `UITableView` only or `UICollectionView` only, that's why I didn't say anything about `titleForHeaderInSection` or `titleForFooterInSection`. But  the current API doesn't allow the library to be extended, I would say we should think about a way to make it easy for people to add missing protocol implementations like `titleForHeaderInSection`.

Regarding the `heightForRowAtIndexPath`, I tested the auto-sizing behavior some time ago, and it worked. The use for `respondsToSelector` is a must. I tried to think about how to go around it, using a dedicated class or protocol. But unfortunately, that wasn't successful. Having a protocol that only implement it makes it hard to use the library, because you need to make every data source in the heirarchy implement it which means you have to subclass each data source. Usually, that's what I do in my code. But someone could use `CompositeDataSource` without subclassing and should handle the sizing with no problem.
