### ISSUE TITLE
Future of project

### ISSUE THREAD

**Issue by ryanjm** [GenericDataSource/GenericDataSource#3]
Hey @mohamede1945 this looks like a great project.

Do you have plans to actively update/maintain this project going forward?

I'm wondering about support for section titles, placeholders, activity indicator, children refreshing parents, etc. Making it more on par with the Apple Example code.

**Comment by mohamede1945** [comment]
Hi @ryanjm, thank you for using it!

Yes, I do plan on keep maintaining the project. If you have some feature requests, please list them and I'll try to put them on my roadmap.

Things, that are in my mind are:

- Section titles 
- SegmentedDataSource
- Network States (loading, error, no data, data loaded)


I cannot remember the thing about children refreshing parents. Can you point me to where it was in the apple sample? I totally forgot how was apple example was since it is been a while since I looked at it. But I'll try to open it again and see what features it has that we can use here.

**Comment by ryanjm** [comment]
I'm glad to hear that. In that case, I'll fork this project and start making pull requests as I start working through it (will you be alright with that?).

It's been a week or two since I watched the WWDC video but they mentioned the idea of having a single spinner for the entire page as content gets loaded. I assume that is what the `didRefreshSections` methods are for within the WWDC project. I won't need that for awhile, but I just wanted to make sure you do want to maintain this project.

I'm just getting into all of this code so it might take me a day or two to get up to speed, but I imagine that section titles will be the first thing I'll run into needing. My first pull request would probably deal with that.

Is there a process you would like me to follow when creating a PR?

**Comment by mohamede1945** [comment]
That looks amazing!

There is no process other than writing tests for new code.

Thank you so much for your help!

**Comment by ryanjm** [comment]
Great!
