### ISSUE TITLE
Pre-select a row?

### ISSUE THREAD

**Issue by ryanjm** [GenericDataSource/GenericDataSource#4]
Are there any hooks that can be used to pre-select a row when the table first gets loaded? I'd normally just have a method that is called on `viewDidLoad` which selects the cells, but since that information is now spread over a couple data sources, I'm not sure what the right way is to do that.

Do I still need to write that method and then have it call each data source? Also, should batch updates be used in this case?

Still trying to get a feel for the project as a whole. 😄

**Comment by ryanjm** [comment]
I've added my own `viewDidLoad` function which is called manually. This seems to work pretty well so far.

**Comment by mohamede1945** [comment]
Ok. Generally, I always do the same thing like you did. Just add it in `viewDidLoad`. Because this is the correct place to do it in your situation, correct?. Now let's assume you have a `UICollectionView` and you want to you have a nested hierarchy of data sources. You want to select an the first cell of an inner data source which happened be the 3rd element in the 2nd section. You have 2 ways:

1. Just use 
```Swift
collectionView.selectItemAtIndexPath(NSIndexPath(forItem: 2, inSection: 1), animated: false, scrollPosition: .Top)
```
But this one needs to know beforehand where is your cell. And if the data source hierarchies is changed, you have to update the code.

2. You can use the data sources.
```Swift
// you might create your data source hierarchies first.
...
// Make sure to have first. 
collectionView.ds_useDataSource(dataSource)
...

// then select the cell by using the data source this way.
innerDataSource.ds_reusableViewDelegate?.ds_selectItemAtIndexPath(NSIndexPath(forItem: 0, inSection: 0), animated: false, scrollPosition: .Top)
```

The advantage of second way is you don't need to know the global index path of your cell anymore.

**Comment by mohamede1945** [comment]
Please reopen if you more info.
